# Generated by Django 3.1.4 on 2021-01-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signupdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('reenterpassword', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
