# Generated by Django 3.1.4 on 2021-01-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyNKSapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdetail',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterModelTable(
            name='signupdetail',
            table='signupdetails',
        ),
    ]
