# Generated by Django 3.1.4 on 2021-01-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyNKSapp', '0002_auto_20210110_2002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signupdetail',
            new_name='signupdetails',
        ),
    ]
