# Generated by Django 3.2.5 on 2021-10-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyNKSapp', '0002_trash_isdeleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trash',
            name='isdeleted',
        ),
    ]
