# Generated by Django 3.1.4 on 2021-01-14 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyNKSapp', '0003_auto_20210110_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='number_of_students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_students', models.IntegerField()),
            ],
            options={
                'db_table': 'number_of_students',
            },
        ),
        migrations.CreateModel(
            name='staff_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'staff_details',
            },
        ),
        migrations.CreateModel(
            name='student_enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=25)),
                ('course', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'student_enroll',
            },
        ),
        migrations.CreateModel(
            name='enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=25)),
                ('course', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyNKSapp.signupdetails')),
            ],
            options={
                'db_table': 'enrolled',
            },
        ),
    ]
