# Generated by Django 3.1.4 on 2021-01-16 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyNKSapp', '0004_enrolled_number_of_students_staff_details_student_enroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='srinadh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sri', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'srinadh',
            },
        ),
        migrations.AddField(
            model_name='student_enroll',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pyNKSapp.signupdetails'),
            preserve_default=False,
        ),
    ]
