# Generated by Django 3.1.4 on 2021-01-16 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyNKSapp', '0005_auto_20210116_1008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='srinadh',
            new_name='srin',
        ),
        migrations.AlterModelTable(
            name='srin',
            table='srin',
        ),
    ]
