# Generated by Django 3.1.4 on 2021-01-16 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyNKSapp', '0006_auto_20210116_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_enroll_desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=25)),
                ('course', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyNKSapp.signupdetails')),
            ],
            options={
                'db_table': 'student_enroll_desc',
            },
        ),
        migrations.DeleteModel(
            name='srin',
        ),
        migrations.DeleteModel(
            name='student_enroll',
        ),
    ]
