# Generated by Django 3.1.4 on 2021-01-16 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyNKSapp', '0007_auto_20210116_1013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student_enroll_desc',
            new_name='student_enrolldesc',
        ),
        migrations.AlterModelTable(
            name='student_enrolldesc',
            table='student_enrolldesc',
        ),
    ]
