# Generated by Django 3.1.4 on 2021-01-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyNKSapp', '0008_auto_20210116_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=25)),
                ('course', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'student_enroll',
            },
        ),
        migrations.DeleteModel(
            name='student_enrolldesc',
        ),
    ]
