# Generated by Django 3.2.5 on 2021-10-04 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyNKSapp', '0009_auto_20210116_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='trash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=300)),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyNKSapp.signupdetails')),
            ],
            options={
                'db_table': 'trash',
            },
        ),
        migrations.CreateModel(
            name='todo_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=300)),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyNKSapp.signupdetails')),
            ],
            options={
                'db_table': 'todo_list',
            },
        ),
    ]
